language: java
jdk:
- openjdk8
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install:
  mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
script:
  mvn clean deploy --settings .maven.xml -B -U -Prelease
deploy:
  provider: releases
  api_key:
    secure: Nme4Am1OPij1n9dbTUceFol2SQygu/Xiy+T+BtYECm4g0hpjWhLoPdUOvjdAu6qPqu92xn1A6w1crXAuWspfWpeFsaGKXGBh2I+Q5hh5EZTt3+e/mhaI3sNx3HLPKkr+2ekaxHk3a/gkywoBt+Q0Y276f/4TCxb+9Q6R8+StxjYkkpJ8rYoUsQbs3e5kiMmGb2hx9XgxF3TzDYqL/Zcrkhat0cB0Doi4DUZAZ5nzhq3l1izfYcpIpmMZobUyl78n1HEpWTZJl6aCbJe0kEKJblEsdvxHrb6VclD6p0Q+FltkoT6V/wfpjxjaMpJWA1rUVl7Em+QTt1ABw2pzoMXUtGXlmBcxBcznuTzvUxD7Oc50CxfzQ+kdxcbRmdbrhGuIqlvwKORf9r9q4xtQ1sV6Y2UGDr7GZl7L7gV7w4IWKJX4rNpepnR+mGjE245swmiWKYpA9C9Hf/eZETfh0MuuVsIf9QrLrFPFBm3xFaeFqd+YzLOCH1ElSqf2jfy34E/RlVwE+L+KORHtxMvx+fGevu6hhqe1AyWM/w1p4S2jDjHgSvZ716AmPgP3VBl4+AZ1aQOILOYvUIAoQNP9LdJeTC86TO5ab537AjTouHWZEmFnXGSeaVI51blzB1qvH1c/gqrZGschi275QqHLf46hsILGpl+jGA3Ha+NVhfw18RA=
  file:
    - annotations/target/annotations-$project_version.jar
    - annotations/target/annotations-$project_version-javadoc.jar
    - annotations/target/annotations-$project_version-sources.jar
    - api/target/mcspring-$project_version.jar
    - api/target/mcspring-$project_version-javadoc.jar
    - api/target/mcspring-$project_version-sources.jar
    - api-vault/target/mcspring-vault-$project_version.jar
    - api-vault/target/mcspring-vault-$project_version-javadoc.jar
    - api-vault/target/mcspring-vault-$project_version-sources.jar
    - archetype/target/archetype-$project_version.jar
    - subcommands/target/subcommands-$project_version.jar
    - subcommands/target/subcommands-$project_version-javadoc.jar
    - subcommands/target/subcommands-$project_version-sources.jar
  skip_cleanup: true
  on:
    repo: kylepls/mc-spring
  name: $project_version
